### ISSUE TITLE
I dont like it

### ISSUE THREAD

**Issue by kev1nl1u** [DavideSirico/Blog#3]
I just dont like it. delete.
<img width="960" alt="sainz" src="https://github.com/DavideSirico/Blog/assets/87583569/3cc9c733-a752-4990-94be-27c4f987bd62">

**Comment by DavideSirico** [comment]
idc
![Primo-vlog-di-SurrealPower-2012-1024x683](https://github.com/DavideSirico/Blog/assets/34192863/96f4e456-112d-483e-9b50-b7f7cef6317f)
